### ISSUE TITLE
L-SMASH-Worksのファイルたちのの重複

### ISSUE THREAD

**Issue by nyanrus** [karoterra/aviutl-hash-finder#2]
Auto_Buildからダウンロードするので効率が悪い
先にリストを取得後、重複をなくしてダウンロードしたほうがいいと思います
後で #1 と合わせるのもあり

**Comment by karoterra** [comment]
「重複をなくす」というのが具体的にどういうことか分からないので、教えて頂けると助かります。

**Comment by nyanrus** [comment]
L-SMASH-Worksの場合、Auto_Buildで毎日ビルドされますが、バージョンの変動がなかったりするので
すべてのReleasesをダウンロードする場合時間と容量的な側面で効率が悪いです。
L-SMASH-Worksはファイル名でバージョンを判断できるので
ReleasesのListからファイル名を基準にして、同じファイル名の場合その中の一つだけダウンロードする。ということです

**Comment by nyanrus** [comment]
あー…残念ながらハッシュが全部違うみたいですね。。。

**Comment by karoterra** [comment]
ffmpegが頻繁に更新されているのでL-SMASH Worksのソースが更新されていなくてもビルドされたバイナリは基本的に変わってしまいますね…。
構成でハッシュが変わっていない例ならわずかに確認できましたが。
- `Mr-Ojii_l-smash build-2022-07-31-02-44-27` と `Mr-Ojii_Mr-Ojii build-2022-07-31-02-44-27` の `lwcolor.auc` が同じ
- `HolyWu_l-smash build-2022-05-03-12-52-01` と `HolyWu_Mr-Ojii build-2022-05-03-12-52-01` の `lwcolor.auc` が同じ

**Comment by nyanrus** [comment]
不思議なことにamateさんの設定ダイアログ画面サイズ固定化プラグインもv1.1とv1.2がハッシュが同じなようですね。
まぁこの件はどうしようも無いということで了解しました。
